from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.portal_landing, name='portal_landing'),
    path('home/', views.home, name='home'),
    path('complaints/', views.complaints_dashboard, name='complaints_dashboard'),
    path('complaints/submit/', views.complaint_submit, name='complaint_submit'),
    path('complaints/<int:pk>/', views.complaint_detail, name='complaint_detail'),
    path('complaints/<int:pk>/assign-inspector/', views.complaint_assign_inspector, name='complaint_assign_inspector'),
    path('complaints/<int:pk>/inspection/save/', views.complaint_inspection_save, name='complaint_inspection_save'),
    path('complaints/<int:pk>/assign-supervisor/', views.complaint_assign_supervisor, name='complaint_assign_supervisor'),
    path('complaints/<int:pk>/resolution/save/', views.complaint_resolution_save, name='complaint_resolution_save'),
    path('complaints/<int:pk>/photos/add/', views.complaint_add_photos, name='complaint_add_photos'),
    path('complaints/<int:pk>/photos/<int:photo_pk>/delete/', views.complaint_photo_delete, name='complaint_photo_delete'),
    path('complaints/pdf-import/', views.complaint_pdf_import, name='complaint_pdf_import'),
    path('complaints/pdf-import/review/', views.complaint_pdf_review, name='complaint_pdf_review'),
    path('complaints/set-language/', views.set_complaints_language, name='set_complaints_language'),
    path('complaints/all-requests/', views.all_requests, name='all_requests'),

    # Container transfer requests
    path('container-transfers/', views.container_list, name='container_list'),
    path('container-transfers/new/', views.container_create, name='container_create'),
    path('container-transfers/pdf-import/', views.container_pdf_import, name='container_pdf_import'),
    path('container-transfers/pdf-import/review/', views.container_pdf_review, name='container_pdf_review'),
    path('container-transfers/<int:pk>/', views.container_detail, name='container_detail'),
    path('container-transfers/<int:pk>/assign-inspector/', views.container_assign_inspector, name='container_assign_inspector'),
    path('container-transfers/<int:pk>/save-location/', views.container_save_location, name='container_save_location'),
    path('container-transfers/<int:pk>/contact-biaa/', views.container_contact_biaa, name='container_contact_biaa'),
    path('container-transfers/<int:pk>/mark-transferred/', views.container_mark_transferred, name='container_mark_transferred'),
    path('container-transfers/<int:pk>/submit-report/', views.container_submit_report, name='container_submit_report'),
    path('container-transfers/<int:pk>/close/', views.container_close, name='container_close'),
    path('container-transfers/<int:pk>/reject/', views.container_reject, name='container_reject'),
    path('container-transfers/<int:pk>/photos/<int:photo_pk>/delete/', views.container_photo_delete, name='container_photo_delete'),

    # Weed Removal
    path('weed-removal/', views.weed_list, name='weed_list'),
    path('weed-removal/create/', views.weed_create, name='weed_create'),
    path('weed-removal/<int:pk>/save-location/', views.weed_save_location, name='weed_save_location'),
    path('weed-removal/pdf-import/', views.weed_pdf_import, name='weed_pdf_import'),
    path('weed-removal/pdf-review/', views.weed_pdf_review, name='weed_pdf_review'),
    path('weed-removal/<int:pk>/', views.weed_detail, name='weed_detail'),
    path('weed-removal/<int:pk>/assign-inspector/', views.weed_assign_inspector, name='weed_assign_inspector'),
    path('weed-removal/<int:pk>/inspector-done/', views.weed_inspector_done, name='weed_inspector_done'),
    path('weed-removal/<int:pk>/assign-supervisor/', views.weed_assign_supervisor, name='weed_assign_supervisor'),
    path('weed-removal/<int:pk>/supervisor-start/', views.weed_supervisor_start, name='weed_supervisor_start'),
    path('weed-removal/<int:pk>/add-vehicle/', views.weed_add_vehicle, name='weed_add_vehicle'),
    path('weed-removal/<int:pk>/delete-vehicle/<int:vpk>/', views.weed_delete_vehicle, name='weed_delete_vehicle'),
    path('weed-removal/<int:pk>/upload-photos/', views.weed_upload_photos, name='weed_upload_photos'),
    path('weed-removal/<int:pk>/supervisor-done/', views.weed_supervisor_done, name='weed_supervisor_done'),
    path('weed-removal/<int:pk>/reject/', views.weed_reject, name='weed_reject'),
    path('weed-removal/<int:pk>/close/', views.weed_close, name='weed_close'),
    path('weed-removal/<int:pk>/photos/<int:ppk>/delete/', views.weed_photo_delete, name='weed_photo_delete'),

    path('companies/', views.company_list, name='company_list'),
    path('company_detail/<int:id>/', views.company_detail, name='company_detail'),
    path(
        'company_detail/requirements-insurance/<int:request_id>/',
        views.requirement_insurance_request_detail,
        name='requirement_insurance_request_detail',
    ),
    path(
        'permits/requirements-insurance/',
        views.requirement_insurance_create,
        name='requirement_insurance_create',
    ),
    path('add_company/', views.add_company, name='add_company'),
    path('extensions/followup/', views.extension_followup, name='extension_followup'),
    path('enginers/', views.enginer_list, name='enginer_list'),
    path('enginers/add/', views.enginer_add, name='enginer_add'),
    path('enginers/<int:id>/', views.enginer_detail, name='enginer_detail'),
    path('enginers/public-health-exam-requests/', views.public_health_exam_request_list, name='public_health_exam_request_list'),
    path('enginers/public-health-exam-requests/<int:request_id>/', views.public_health_exam_request_detail, name='public_health_exam_request_detail'),
    path('enginers/certificate-requests/', views.engineer_certificate_request_list, name='engineer_certificate_request_list'),
    path('enginers/certificate-requests/<int:request_id>/', views.engineer_certificate_request_detail, name='engineer_certificate_request_detail'),
    path('clearances/', views.clearance_list, name='clearance_list'),
    path('permits/', views.permit_types, name='permit_types'),
    path('permits/report/excel/', views.permits_report_excel, name='permits_report_excel'),
    path('permits/report/inspectors/', views.inspector_report_excel, name='inspector_report_excel'),
    path('permits/pest-control/', views.pest_control_permit, name='pest_control_permit'),
    path('permits/vehicle/', views.vehicle_permit, name='vehicle_permit'),
    path('permits/waste/', views.waste_permit, name='waste_permit'),
    path('permits/pest-control/<int:id>/', views.pest_control_permit_detail, name='pest_control_permit_detail'),
    path('permits/vehicle/<int:id>/', views.vehicle_permit_detail, name='vehicle_permit_detail'),
    path('permits/waste/<int:id>/', views.waste_permit_detail, name='waste_permit_detail'),
    path('permits/waste/<int:permit_id>/disposals/new/', views.waste_disposal_request_detail, name='waste_disposal_request_new'),
    path('permits/waste/<int:permit_id>/disposals/<int:request_id>/', views.waste_disposal_request_detail, name='waste_disposal_request_detail'),
    path('permits/pest-control/<int:id>/view/', views.pest_control_permit_view, name='pest_control_permit_view'),
    path('permits/pest-control/<int:id>/print/', views.pest_control_permit_print, name='pest_control_permit_print'),
    path('permits/waste/<int:permit_id>/print/', views.waste_disposal_permit_print, name='waste_disposal_permit_print'),
    path('permits/vehicle/<int:permit_id>/print/', views.vehicle_permit_print, name='vehicle_permit_print'),
    path('permits/engineer-addition/', views.engineer_addition_create, name='engineer_addition_create'),
    path('permits/engineer-addition/<int:id>/', views.engineer_addition_detail, name='engineer_addition_detail'),
    path('printer/', views.printer, name='printer'),
    path('printer/<int:permit_id>/', views.printer, name='printer_permit'),
    path('pirmet/<int:id>/', views.pest_control_permit_detail, name='pirmet_detail'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.html',
            email_template_name='registration/password_reset_email.html',
            subject_template_name='registration/password_reset_subject.txt',
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    path('field-work/', views.field_work_list, name='field_work_list'),
    path('field-work/create/', views.field_work_create, name='field_work_create'),
    path('field-work/<int:pk>/', views.field_work_detail, name='field_work_detail'),
    path('field-work/<int:pk>/report/', views.field_work_report, name='field_work_report'),
]
