from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.portal_landing, name='portal_landing'),
    path('home/', views.home, name='home'),
    path('complaints/', views.complaints_dashboard, name='complaints_dashboard'),
    path('complaints/submit/', views.complaint_submit, name='complaint_submit'),
    path('complaints/<int:pk>/', views.complaint_detail, name='complaint_detail'),
    path('complaints/<int:pk>/assign-inspector/', views.complaint_assign_inspector, name='complaint_assign_inspector'),
    path('complaints/<int:pk>/inspection/save/', views.complaint_inspection_save, name='complaint_inspection_save'),
    path('complaints/<int:pk>/assign-supervisor/', views.complaint_assign_supervisor, name='complaint_assign_supervisor'),
    path('complaints/<int:pk>/resolution/save/', views.complaint_resolution_save, name='complaint_resolution_save'),
    path('complaints/<int:pk>/photos/add/', views.complaint_add_photos, name='complaint_add_photos'),
    path('complaints/<int:pk>/photos/<int:photo_pk>/delete/', views.complaint_photo_delete, name='complaint_photo_delete'),
    path('complaints/set-language/', views.set_complaints_language, name='set_complaints_language'),
    path('companies/', views.company_list, name='company_list'),
    path('company_detail/<int:id>/', views.company_detail, name='company_detail'),
    path(
        'company_detail/requirements-insurance/<int:request_id>/',
        views.requirement_insurance_request_detail,
        name='requirement_insurance_request_detail',
    ),
    path(
        'permits/requirements-insurance/',
        views.requirement_insurance_create,
        name='requirement_insurance_create',
    ),
    path('add_company/', views.add_company, name='add_company'),
    path('extensions/followup/', views.extension_followup, name='extension_followup'),
    path('enginers/', views.enginer_list, name='enginer_list'),
    path('enginers/add/', views.enginer_add, name='enginer_add'),
    path('enginers/<int:id>/', views.enginer_detail, name='enginer_detail'),
    path('enginers/public-health-exam-requests/', views.public_health_exam_request_list, name='public_health_exam_request_list'),
    path('enginers/public-health-exam-requests/<int:request_id>/', views.public_health_exam_request_detail, name='public_health_exam_request_detail'),
    path('enginers/certificate-requests/', views.engineer_certificate_request_list, name='engineer_certificate_request_list'),
    path('enginers/certificate-requests/<int:request_id>/', views.engineer_certificate_request_detail, name='engineer_certificate_request_detail'),
    path('clearances/', views.clearance_list, name='clearance_list'),
    path('permits/', views.permit_types, name='permit_types'),
    path('permits/report/excel/', views.permits_report_excel, name='permits_report_excel'),
    path('permits/report/inspectors/', views.inspector_report_excel, name='inspector_report_excel'),
    path('permits/pest-control/', views.pest_control_permit, name='pest_control_permit'),
    path('permits/vehicle/', views.vehicle_permit, name='vehicle_permit'),
    path('permits/waste/', views.waste_permit, name='waste_permit'),
    path('permits/pest-control/<int:id>/', views.pest_control_permit_detail, name='pest_control_permit_detail'),
    path('permits/vehicle/<int:id>/', views.vehicle_permit_detail, name='vehicle_permit_detail'),
    path('permits/waste/<int:id>/', views.waste_permit_detail, name='waste_permit_detail'),
    path('permits/waste/<int:permit_id>/disposals/new/', views.waste_disposal_request_detail, name='waste_disposal_request_new'),
    path('permits/waste/<int:permit_id>/disposals/<int:request_id>/', views.waste_disposal_request_detail, name='waste_disposal_request_detail'),
    path('permits/pest-control/<int:id>/view/', views.pest_control_permit_view, name='pest_control_permit_view'),
    path('permits/pest-control/<int:id>/print/', views.pest_control_permit_print, name='pest_control_permit_print'),
    path('permits/waste/<int:permit_id>/print/', views.waste_disposal_permit_print, name='waste_disposal_permit_print'),
    path('permits/vehicle/<int:permit_id>/print/', views.vehicle_permit_print, name='vehicle_permit_print'),
    path('permits/engineer-addition/', views.engineer_addition_create, name='engineer_addition_create'),
    path('permits/engineer-addition/<int:id>/', views.engineer_addition_detail, name='engineer_addition_detail'),
    path('printer/', views.printer, name='printer'),
    path('printer/<int:permit_id>/', views.printer, name='printer_permit'),
    path('pirmet/<int:id>/', views.pest_control_permit_detail, name='pirmet_detail'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.html',
            email_template_name='registration/password_reset_email.html',
            subject_template_name='registration/password_reset_subject.txt',
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
]
