# Generated by Django 6.0 on 2026-01-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyDocuments',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/'),
        ),
        migrations.CreateModel(
            name='PirmetClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfCreation', models.DateField(auto_now_add=True)),
                ('dateOfExpiry', models.DateField()),
                ('PaymentNumber', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcsd.company')),
            ],
        ),
    ]
