# Generated by Django 6.0 on 2026-01-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0002_company_companydocuments_pirmetclearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('review_pending', 'Pending Inspector Review'), ('approved', 'Approved - Payment Link Sent'), ('payment_pending', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=25),
        ),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='PaymentNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DisposalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectionFee', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('feePaid', models.BooleanField(default=False)),
                ('feePaidDate', models.DateTimeField(blank=True, null=True)),
                ('pirmet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hcsd.pirmetclearance')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectionDate', models.DateTimeField(auto_now_add=True)),
                ('approval', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('reportNotes', models.TextField()),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('disposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hcsd.disposalprocess')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcsd.enginer')),
            ],
        ),
        migrations.CreateModel(
            name='InspectorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcsd.enginer')),
                ('pirmet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hcsd.pirmetclearance')),
            ],
        ),
    ]
