# Generated by Django 6.0 on 2026-01-20 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0003_pirmetclearance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='approvedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pirmets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='approvedRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='unapprovedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unapproved_pirmets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='unapprovedReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
