# Generated by Django 6.0 on 2026-01-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0004_pirmetclearance_approvedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('review_pending', 'Pending Inspector Review'), ('approved', 'Approved - Payment Link Sent'), ('payment_pending', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('issued', 'Issued'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=25),
        ),
        migrations.CreateModel(
            name='PirmetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pirmet_documents/')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('pirmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hcsd.pirmetclearance')),
            ],
        ),
    ]
