# Generated by Django 6.0 on 2026-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0005_alter_pirmetclearance_status_pirmetdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('review_pending', 'Pending Inspector Review'), ('rejected', 'Rejected'), ('approved', 'Approved - Payment Link Sent'), ('payment_pending', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('issued', 'Issued'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=25),
        ),
    ]
