# Generated by Django 6.0 on 2026-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0006_alter_pirmetclearance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_activity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_license_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='allowed_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='allowed_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='company_rep',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='department_stamp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='permit_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='restricted_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='restricted_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
