# Generated by Django 6.0 on 2026-02-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0007_add_pirmet_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PirmetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Changed'), ('payment_update', 'Payment Updated'), ('document_upload', 'Documents Uploaded'), ('details_update', 'Details Updated')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=25, null=True)),
                ('new_status', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('pirmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='hcsd.pirmetclearance')),
            ],
        ),
    ]
