# Generated by Django 6.0 on 2026-02-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0008_add_pirmet_change_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enginer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='hcsd.enginer',
            ),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='permit_type',
            field=models.CharField(
                choices=[
                    ('pest_control', 'Pest Control Permit'),
                    ('pesticide_transport', 'Pesticide Transport Permit'),
                    ('waste_disposal', 'Waste Disposal Permit'),
                ],
                default='pest_control',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PesticideTransportPermit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'contact_number',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'activity_type',
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    'vehicle_type',
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    'vehicle_color',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'vehicle_number',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'vehicle_license_expiry',
                    models.DateField(blank=True, null=True),
                ),
                (
                    'issue_authority',
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    'pirmet',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transport_details',
                        to='hcsd.pirmetclearance',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='WasteDisposalPermit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'waste_classification',
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    'waste_quantity_monthly',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ('waste_types', models.TextField(blank=True, null=True)),
                (
                    'material_state',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'project_number',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'project_type',
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    'contractors',
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    'employee_number',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'pirmet',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='waste_details',
                        to='hcsd.pirmetclearance',
                    ),
                ),
            ],
        ),
    ]
