# Generated by Django 6.0 on 2026-01-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0011_add_company_pest_control_type'),
        ('hcsd', '0011_alter_pirmetclearance_status'),
    ]

    operations = [
    ]
