# Generated by Django 6.0 on 2026-01-27

from django.db import migrations, models


def forwards(apps, schema_editor):
    PirmetClearance = apps.get_model('hcsd', 'PirmetClearance')
    PirmetClearance.objects.filter(status='rejected').update(status='needs_completion')


def backwards(apps, schema_editor):
    PirmetClearance = apps.get_model('hcsd', 'PirmetClearance')
    PirmetClearance.objects.filter(status='needs_completion').update(status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0012_merge_20260127_0421'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(
                choices=[
                    ('order_received', 'Order Received'),
                    ('review_pending', 'Pending Inspector Review'),
                    ('needs_completion', 'Needs Completion'),
                    ('approved', 'Inspector Approved'),
                    ('payment_pending', 'Waiting for Payment'),
                    ('payment_completed', 'Payment Completed'),
                    ('issued', 'Issued'),
                    ('inspection_pending', 'Inspection Pending'),
                    ('inspection_completed', 'Inspection Completed'),
                    ('disposal_approved', 'Disposal Approved'),
                    ('disposal_rejected', 'Disposal Rejected'),
                ],
                default='order_received',
                max_length=25,
            ),
        ),
    ]
