# Generated by Django 6.0 on 2026-01-27

import datetime

from django.db import migrations, models
from django.db.models import Count, Q


def _make_permit_no(obj):
    year = obj.dateOfCreation.year if obj.dateOfCreation else datetime.date.today().year
    return f"PRM-{year}-{obj.pk:06d}"


def forwards(apps, schema_editor):
    PirmetClearance = apps.get_model('hcsd', 'PirmetClearance')

    missing_qs = PirmetClearance.objects.filter(
        Q(permit_no__isnull=True) | Q(permit_no='')
    )
    for obj in missing_qs.iterator():
        obj.permit_no = _make_permit_no(obj)
        obj.save(update_fields=['permit_no'])

    duplicates = (
        PirmetClearance.objects.exclude(permit_no__isnull=True)
        .exclude(permit_no='')
        .values('permit_no')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for row in duplicates:
        dup_qs = PirmetClearance.objects.filter(permit_no=row['permit_no']).order_by('id')
        first = True
        for obj in dup_qs.iterator():
            if first:
                first = False
                continue
            obj.permit_no = _make_permit_no(obj)
            obj.save(update_fields=['permit_no'])


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0013_add_needs_completion_status'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='permit_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
