# Generated by Django 6.0 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0014_auto_permit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginer',
            name='public_health_cert',
            field=models.FileField(blank=True, null=True, upload_to='engineer_certificates/'),
        ),
        migrations.AddField(
            model_name='enginer',
            name='termite_cert',
            field=models.FileField(blank=True, null=True, upload_to='engineer_certificates/'),
        ),
        migrations.CreateModel(
            name='EnginerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('public_health_cert_uploaded', 'Public Health Certificate Uploaded'), ('termite_cert_uploaded', 'Termite Certificate Uploaded')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enginer', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='status_logs', to='hcsd.enginer')),
            ],
        ),
    ]
