# Generated by Django 6.0 on 2026-01-27

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Enginer = apps.get_model('hcsd', 'Enginer')
    EnginerStatusLog = apps.get_model('hcsd', 'EnginerStatusLog')

    for enginer in Enginer.objects.all():
        has_created = EnginerStatusLog.objects.filter(
            enginer=enginer, action='created'
        ).exists()
        if not has_created:
            log = EnginerStatusLog.objects.create(
                enginer=enginer,
                action='created',
            )
            EnginerStatusLog.objects.filter(pk=log.pk).update(
                created_at=timezone.now()
            )


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0015_enginer_certifications_and_logs'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
