# Generated by Django 6.0 on 2026-01-28

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Company = apps.get_model('hcsd', 'Company')
    CompanyChangeLog = apps.get_model('hcsd', 'CompanyChangeLog')

    for company in Company.objects.all():
        has_created = CompanyChangeLog.objects.filter(
            company=company, action='created'
        ).exists()
        if not has_created:
            log = CompanyChangeLog.objects.create(
                company=company,
                action='created',
            )
            CompanyChangeLog.objects.filter(pk=log.pk).update(
                created_at=timezone.now()
            )


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0017_company_change_log'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
