# Generated by Django 6.0 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0018_backfill_company_created_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='inspection_payment_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='inspection_payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
