# Generated by Django 6.0 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0019_add_inspection_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('inspection_payment_pending', 'Inspection Payment Pending'), ('review_pending', 'Pending Inspector Review'), ('needs_completion', 'Needs Completion'), ('approved', 'Inspector Approved'), ('payment_pending', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('issued', 'Issued'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=30),
        ),
    ]
