# Generated by Django 6.0 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0020_alter_pirmetclearance_status_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='inspection_payment_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
