# Generated by Django 6.0 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0021_add_payment_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='dateOfExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='inspection_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='pirmet_documents/inspection_receipts/'),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='pirmet_documents/payment_receipts/'),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='request_documents_bundle',
            field=models.FileField(blank=True, null=True, upload_to='pirmet_documents/bundles/'),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='request_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
