# Generated by Django 6.0 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0022_add_pest_control_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychangelog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='company_extension_requests/'),
        ),
    ]
