# Generated by Django 6.0 on 2026-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0023_add_company_extension_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('engineer_changed', 'Engineer Changed'), ('extension_requested', 'Extension Requested')], max_length=40),
        ),
    ]
