# Generated by Django 6.0 on 2026-02-01

from django.db import migrations


def forwards(apps, schema_editor):
    PirmetClearance = apps.get_model('hcsd', 'PirmetClearance')
    for permit in PirmetClearance.objects.all().only('id', 'permit_no').iterator():
        new_value = str(permit.pk)
        if permit.permit_no != new_value:
            permit.permit_no = new_value
            permit.save(update_fields=['permit_no'])


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0024_alter_companychangelog_action'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
