# Generated by Django 6.0 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0025_backfill_permit_no_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
