# Generated by Django 5.1.2 on 2026-02-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0031_enginerstatuslog_archived_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginer',
            name='grain_pests_cert',
            field=models.FileField(blank=True, null=True, upload_to='engineer_certificates/'),
        ),
        migrations.AlterField(
            model_name='enginerstatuslog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('public_health_cert_uploaded', 'Public Health Certificate Uploaded'), ('termite_cert_uploaded', 'Termite Certificate Uploaded'), ('grain_pests_cert_uploaded', 'Grain Pests Certificate Uploaded')], max_length=40),
        ),
    ]
