# Generated by Django 5.1.2 on 2026-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0032_enginer_grain_pests_cert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginer',
            name='grain_pests_cert',
        ),
        migrations.AlterField(
            model_name='enginerstatuslog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('public_health_cert_uploaded', 'Public Health Certificate Uploaded'), ('termite_cert_uploaded', 'Termite Certificate Uploaded')], max_length=40),
        ),
    ]
