# Generated by Django 6.0 on 2026-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0034_alter_company_id_alter_companychangelog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychangelog',
            name='extension_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companychangelog',
            name='extension_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
