# Generated by Django 6.0 on 2026-03-03 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0040_company_location_area_and_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDisposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('disposal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('disposal_payment_receipt', models.FileField(blank=True, null=True, upload_to='pirmet_documents/waste_disposal_receipts/')),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('payment_pending', 'Waiting for Disposal Payment'), ('inspection_pending', 'Inspection Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='payment_pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_inspections', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_disposal_requests', to='hcsd.pirmetclearance')),
            ],
        ),
    ]
