# Generated by Django 6.0 on 2026-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0041_wastedisposalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetchangelog',
            name='new_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pirmetchangelog',
            name='old_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
