# Generated by Django 6.0 on 2026-03-07 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0042_alter_pirmetchangelog_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHealthExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('exam_fee', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('inspector_approved', 'Inspector Approved'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='submitted', max_length=30)),
                ('request_notes', models.TextField(blank=True)),
                ('request_document', models.FileField(blank=True, null=True, upload_to='public_health_exam_requests/documents/')),
                ('review_notes', models.TextField(blank=True)),
                ('payment_link', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='public_health_exam_requests/receipts/')),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('exam_location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_health_exam_requests_created', to=settings.AUTH_USER_MODEL)),
                ('enginer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_health_exam_requests', to='hcsd.enginer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_health_exam_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
