# Generated by Django 6.0 on 2026-03-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0043_publichealthexamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_health_exam_requests', to='hcsd.company'),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='company_trade_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='exam_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='exam_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='exam_result',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='exam_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='identity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='payment_receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='payment_receipt_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='qualified_technician_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='request_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publichealthexamrequest',
            name='unified_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
