# Generated by Django 6.0 on 2026-03-08 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0044_publichealthexamrequest_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publichealthexamrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'بانتظار الاعتماد'), ('inspector_approved', 'تم الاعتماد'), ('payment_pending', 'بانتظار الدفع'), ('scheduled', 'تم حجز الموعد'), ('rejected', 'مرفوض'), ('payment_received', 'بانتظار الدفع'), ('completed', 'مكتمل')], default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='EngineerCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('public_health', 'شهادة اختبار عام'), ('termite', 'شهادة النمل الأبيض')], max_length=30)),
                ('status', models.CharField(choices=[('submitted', 'تم تقديم طلب الشهادة'), ('payment_pending', 'بانتظار سداد رسوم الشهادة'), ('payment_received', 'تم استلام الإيصال والهوية الإماراتية'), ('issued', 'تم إصدار الشهادة'), ('rejected', 'مرفوض')], default='submitted', max_length=30)),
                ('payment_link', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_order_number', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='engineer_certificate_requests/receipts/')),
                ('emirates_id_document', models.FileField(blank=True, null=True, upload_to='engineer_certificate_requests/emirates_id/')),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('issued_certificate', models.FileField(blank=True, null=True, upload_to='engineer_certificate_requests/issued_certificates/')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_certificate_requests_created', to=settings.AUTH_USER_MODEL)),
                ('enginer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='hcsd.enginer')),
                ('exam_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_request', to='hcsd.publichealthexamrequest')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_engineer_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
