# Generated by Django 6.0 on 2026-03-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0045_alter_publichealthexamrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineercertificaterequest',
            name='exam_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_request', to='hcsd.publichealthexamrequest'),
        ),
    ]
