# Generated by Django 6.0 on 2026-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0046_alter_engineercertificaterequest_exam_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineercertificaterequest',
            name='certificate_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enginer',
            name='public_health_cert_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enginer',
            name='termite_cert_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
