# Generated by Django 6.0 on 2026-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0047_engineercertificaterequest_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='violation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='violation_payment_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='violation_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='pirmet_documents/violation_receipts/'),
        ),
    ]
