# Generated by Django 6.0 on 2026-03-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0048_pirmetclearance_violation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='violation_reference_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
