# Generated by Django 6.0 on 2026-03-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0049_pirmetclearance_violation_reference_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDisposalRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pirmet_documents/waste_disposal_request_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disposal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hcsd.wastedisposalrequest')),
            ],
        ),
    ]
