# Generated by Django 6.0 on 2026-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0050_wastedisposalrequestdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='inspection_requires_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='insurance_payment_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='insurance_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='pirmet_documents/insurance_receipts/'),
        ),
    ]
