# Generated by Django 6.0 on 2026-03-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0051_pirmetclearance_inspection_requires_insurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('engineer_changed', 'Engineer Changed'), ('extension_requested', 'Extension Requested'), ('requirements_followup_needed', 'Requirements Follow-up Needed'), ('requirements_insurance_created', 'Requirements Insurance Created'), ('requirements_insurance_paid', 'Requirements Insurance Paid'), ('requirements_insurance_refunded', 'Requirements Insurance Refunded')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('inspection_payment_pending', 'Inspection Payment Pending'), ('review_pending', 'Pending Inspector Review'), ('needs_completion', 'Needs Completion'), ('approved', 'Inspector Approved'), ('payment_pending', 'Waiting for Payment'), ('payment_completed', 'Payment Completed'), ('issued', 'Issued'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('closed_requirements_pending', 'Closed - Requirements Pending'), ('cancelled_admin', 'Cancelled Administratively'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=30),
        ),
        migrations.CreateModel(
            name='RequirementInsuranceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, 'شهر واحد'), (3, '3 أشهر'), (6, '6 أشهر')])),
                ('requirements_notes', models.TextField(blank=True)),
                ('payment_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='requirement_insurance/payment_receipts/')),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('refund_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_receipt', models.FileField(blank=True, null=True, upload_to='requirement_insurance/refund_receipts/')),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'تم إنشاء الطلب'), ('payment_order_recorded', 'تم إدخال أمر دفع التأمين'), ('active', 'تم دفع التأمين'), ('refunded', 'تم استرداد التأمين'), ('cancelled', 'مغلق')], default='created', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_insurance_requests', to='hcsd.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_insurance_requests_created', to=settings.AUTH_USER_MODEL)),
                ('related_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_insurance_requests', to='hcsd.pirmetclearance')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
