# Generated by Django 6.0 on 2026-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0052_alter_companychangelog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='material_state',
            field=models.CharField(choices=[('solid', 'صلبة'), ('gas', 'غازية')], default='solid', max_length=10),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='waste_classification',
            field=models.CharField(choices=[('hazardous', 'المخلفات الخطرة'), ('non_hazardous', 'المخلفات الغير خطرة')], default='hazardous', max_length=20),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='waste_type',
            field=models.CharField(choices=[('empty_pesticide_containers', 'عبوات مبيدات فارغة'), ('general_waste', 'نفايات عامة'), ('sorted_dry_waste', 'نفايات جافة مفرزة'), ('green_waste', 'المخلفات الخضراء'), ('tires', 'إطارات'), ('commercial_industrial_waste', 'المخلفات التجارية والصناعية'), ('wood', 'خشب'), ('liquid_waste', 'النفايات السائلة'), ('construction_demolition_waste', 'مخلفات الهدم والبناء')], default='empty_pesticide_containers', max_length=40),
        ),
    ]
