# Generated by Django 6.0 on 2026-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0055_fix_companychangelog_action_maxlength_and_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('engineer_changed', 'Engineer Changed'), ('extension_requested', 'Extension Requested'), ('extension_closed', 'Extension Closed'), ('requirements_followup_needed', 'Requirements Follow-up Needed'), ('requirements_insurance_created', 'Requirements Insurance Created'), ('requirements_insurance_paid', 'Requirements Insurance Paid'), ('requirements_insurance_refunded', 'Requirements Insurance Refunded'), ('waste_permit_created', 'Waste Permit Created'), ('waste_permit_payment_reference', 'Waste Permit Payment Reference'), ('waste_permit_paid', 'Waste Permit Paid'), ('waste_permit_issued', 'Waste Permit Issued'), ('waste_request_created', 'Waste Request Created'), ('waste_request_payment_reference', 'Waste Request Payment Reference'), ('waste_request_paid', 'Waste Request Paid'), ('waste_request_inspected', 'Waste Request Inspected')], max_length=60),
        ),
    ]
