# Generated by Django 6.0 on 2026-03-16 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0059_add_violation_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='head_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_approved_pirmets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='head_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirmetclearance',
            name='head_approved_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
