# Generated by Django 6.0 on 2026-03-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0060_add_head_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('inspection_payment_pending', 'Inspection Payment Pending'), ('review_pending', 'Pending Inspector Review'), ('needs_completion', 'Needs Completion'), ('approved', 'Inspector Approved'), ('payment_pending', 'Waiting for Payment'), ('issued', 'Issued'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('violation_payment_link_pending', 'Violation Payment Link Pending'), ('violation_payment_pending', 'Violation Payment Pending'), ('head_approved', 'الاعتماد النهائي'), ('closed_requirements_pending', 'Closed - Requirements Pending'), ('cancelled_admin', 'Cancelled Administratively'), ('disposal_approved', 'Disposal Approved'), ('disposal_rejected', 'Disposal Rejected')], default='order_received', max_length=30),
        ),
        migrations.CreateModel(
            name='PublicHealthExamRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='public_health_exam_requests/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hcsd.publichealthexamrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
