# Generated by Django 6.0 on 2026-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0061_add_exam_request_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginer',
            name='public_health_cert_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enginer',
            name='termite_cert_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
