# Generated by Django 6.0 on 2026-04-09 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0062_add_cert_expiry_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=100, verbose_name='رقم الشكوى')),
                ('pdf_file', models.FileField(upload_to='complaints/pdfs/', verbose_name='ملف الشكوى (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوي',
                'ordering': ['-created_at'],
            },
        ),
    ]
