# Generated by Django 6.0 on 2026-04-09 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0063_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('assigned_inspector', 'بانتظار التفتيش'), ('inspection_done', 'اكتمل التفتيش'), ('assigned_supervisor', 'بانتظار المعالجة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ComplaintInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('location_notes', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='ملاحظات التفتيش')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_inspections_assigned', to=settings.AUTH_USER_MODEL, verbose_name='أسند بواسطة')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='hcsd.complaint', verbose_name='الشكوى')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
            ],
            options={
                'verbose_name': 'تفتيش شكوى',
                'verbose_name_plural': 'تفتيش الشكاوي',
            },
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('inspection', 'صور التفتيش'), ('during_work', 'صور أثناء العمل'), ('after_work', 'صور بعد الانتهاء')], max_length=20, verbose_name='المرحلة')),
                ('file', models.ImageField(upload_to='complaints/photos/', verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hcsd.complaint', verbose_name='الشكوى')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_photos', to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة')),
            ],
            options={
                'verbose_name': 'صورة شكوى',
                'verbose_name_plural': 'صور الشكاوي',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('num_workers', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد العمال')),
                ('num_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأيام')),
                ('work_notes', models.TextField(blank=True, verbose_name='ملاحظات المعالجة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_resolutions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='أسند بواسطة')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='hcsd.complaint', verbose_name='الشكوى')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='المراقب')),
            ],
            options={
                'verbose_name': 'معالجة شكوى',
                'verbose_name_plural': 'معالجة الشكاوي',
            },
        ),
        migrations.CreateModel(
            name='ComplaintVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, verbose_name='رقم اللوحة')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المركبة')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='hcsd.complaintresolution', verbose_name='المعالجة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
            },
        ),
    ]
