# Generated by Django 6.0 on 2026-04-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0064_alter_complaint_status_complaintinspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(blank=True, max_length=200, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='موبايل المتعامل'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المتعامل'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم المنزل'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pest_types',
            field=models.CharField(blank=True, max_length=200, verbose_name='أنواع الآفات'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الشارع'),
        ),
        migrations.AddField(
            model_name='complaintresolution',
            name='closing_status',
            field=models.CharField(blank=True, choices=[('ok', 'تم التنفيذ (OK)'), ('no_answer', 'لا يوجد رد'), ('private_company', 'أُحيل لشركة خاصة'), ('need_ulv', 'يحتاج رش ULV'), ('need_approval', 'يحتاج موافقة'), ('no_need', 'لا يحتاج تدخل')], max_length=20, verbose_name='حالة الإغلاق'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='complaints/pdfs/', verbose_name='ملف الشكوى (PDF)'),
        ),
        migrations.CreateModel(
            name='ComplaintMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=150, verbose_name='اسم المادة')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='الكمية')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hcsd.complaintresolution', verbose_name='المعالجة')),
            ],
            options={
                'verbose_name': 'مادة كيميائية',
                'verbose_name_plural': 'المواد الكيميائية',
            },
        ),
    ]
