# Generated by Django 6.0 on 2026-04-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0065_complaint_area_complaint_complainant_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetclearance',
            name='engineer_to_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addition_requests', to='hcsd.enginer'),
        ),
        migrations.AlterField(
            model_name='enginer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='permit_type',
            field=models.CharField(choices=[('pest_control', 'Pest Control Permit'), ('pesticide_transport', 'Pesticide Transport Permit'), ('waste_disposal', 'Waste Disposal Permit'), ('engineer_addition', 'Engineer Addition Request')], default='pest_control', max_length=30),
        ),
    ]
