# Generated by Django 6.0 on 2026-04-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0066_pirmetclearance_engineer_to_add_alter_enginer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pirmets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pirmetclearance',
            name='unapprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unapproved_pirmets', to=settings.AUTH_USER_MODEL),
        ),
    ]
