# Generated by Django 6.0 on 2026-04-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0067_fix_approvedby_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200, verbose_name='نوع العمل')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='وصف العمل')),
                ('work_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('workers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد العمال')),
                ('equipment_used', models.TextField(blank=True, verbose_name='المعدات المستخدمة')),
                ('work_completed', models.BooleanField(blank=True, null=True, verbose_name='اكتملت العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التنفيذ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('incomplete', 'غير مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_orders', to='hcsd.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'أمر عمل ميداني',
                'verbose_name_plural': 'أوامر العمل الميداني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('before', 'قبل العمل'), ('during', 'أثناء العمل'), ('after', 'بعد العمل')], max_length=10, verbose_name='المرحلة')),
                ('file', models.ImageField(upload_to='field_work/photos/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_photos', to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hcsd.fieldworkorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'صورة عمل ميداني',
                'verbose_name_plural': 'صور العمل الميداني',
                'ordering': ['phase', 'uploaded_at'],
            },
        ),
    ]
