# Generated by Django 6.0 on 2026-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0068_field_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldworkorder',
            name='company',
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='fieldworkorder',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='العنوان'),
        ),
    ]
