# Generated by Django 6.0 on 2026-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0069_field_work_replace_company_with_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirmetdocument',
            name='doc_type',
            field=models.CharField(choices=[('engineer_doc', 'مستند مهندس'), ('inspection_photo', 'صورة/مستند تفتيش')], default='engineer_doc', max_length=30),
        ),
        migrations.AddField(
            model_name='pirmetdocument',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
