# Generated by Django 6.0 on 2026-04-21 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0070_pirmetdocument_add_doc_type_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=100, verbose_name='رقم الشكوى')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='container_requests/pdfs/', verbose_name='ملف PDF')),
                ('complainant_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتعامل')),
                ('complainant_mobile', models.CharField(blank=True, max_length=30, verbose_name='رقم الموبايل')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='المنطقة')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المنزل')),
                ('notes', models.TextField(blank=True, verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('assigned', 'بانتظار المفتش'), ('location_saved', 'تم حفظ الموقع'), ('biaa_contacted', 'تم التواصل مع بيئة'), ('biaa_transferred', 'تم نقل الحاوية'), ('report_submitted', 'تم تقديم التقرير'), ('closed', 'مغلق')], default='new', max_length=30, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
            ],
            options={
                'verbose_name': 'طلب نقل حاوية',
                'verbose_name_plural': 'طلبات نقل الحاويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTransferPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('before', 'صور قبل النقل'), ('after', 'صور بعد النقل')], max_length=10, verbose_name='المرحلة')),
                ('file', models.ImageField(upload_to='container_requests/photos/', verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_photos', to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hcsd.containertransferrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'صورة حاوية',
                'verbose_name_plural': 'صور الحاويات',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTransferInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('location_notes', models.TextField(blank=True, verbose_name='ملاحظات الموقع')),
                ('location_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت حفظ الموقع')),
                ('biaa_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التواصل مع بيئة')),
                ('biaa_contact_notes', models.TextField(blank=True, verbose_name='ملاحظات التواصل مع بيئة')),
                ('biaa_transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت نقل الحاوية')),
                ('report_notes', models.TextField(blank=True, verbose_name='ملاحظات التقرير')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_inspections_assigned', to=settings.AUTH_USER_MODEL, verbose_name='أسند بواسطة')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='hcsd.containertransferrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تفتيش طلب حاوية',
                'verbose_name_plural': 'تفتيش طلبات الحاويات',
            },
        ),
    ]
