# Generated by Django 6.0 on 2026-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0071_containertransferrequest_containertransferphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertransferinspection',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='containertransferinspection',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
