# Generated by Django 6.0 on 2026-04-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0072_alter_containertransferinspection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='area',
            field=models.CharField(blank=True, max_length=200, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المتعامل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='excel_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='حالة الطلب (Excel)'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='excel_status_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='ملاحظة الحالة (Excel)'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم المنزل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='الموبايل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='month_sheet',
            field=models.CharField(blank=True, max_length=20, verbose_name='الشهر'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='رقم الطلب'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='pest_types',
            field=models.CharField(blank=True, max_length=300, verbose_name='نوع الحشرات'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('excel', 'مستورد من Excel')], default='manual', max_length=10, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الشارع'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='المشرف المعالج'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_ant',
            field=models.BooleanField(default=False, verbose_name='نمل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_bees',
            field=models.BooleanField(default=False, verbose_name='نحل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_cockroach',
            field=models.BooleanField(default=False, verbose_name='صراصير'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_fly',
            field=models.BooleanField(default=False, verbose_name='ذباب'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_mosquito',
            field=models.BooleanField(default=False, verbose_name='بعوض'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_other',
            field=models.BooleanField(default=False, verbose_name='أخرى'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_rat',
            field=models.BooleanField(default=False, verbose_name='فئران'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_scorpion',
            field=models.BooleanField(default=False, verbose_name='عقارب'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_snake',
            field=models.BooleanField(default=False, verbose_name='ثعبان'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='treated_wasps',
            field=models.BooleanField(default=False, verbose_name='دبابير'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_boom',
            field=models.BooleanField(default=False, verbose_name='BOOM'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_cyphorce',
            field=models.BooleanField(default=False, verbose_name='CYPHORCE'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_diesel',
            field=models.BooleanField(default=False, verbose_name='DIESEL'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_difron',
            field=models.BooleanField(default=False, verbose_name='DIFRON 25 SC'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_eco_larvacide',
            field=models.BooleanField(default=False, verbose_name='ECO LARVACIDE'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_fly_attractant',
            field=models.BooleanField(default=False, verbose_name='FLY ATTRACTANT'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_graibait',
            field=models.BooleanField(default=False, verbose_name='GRAIBAIT'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_hymenopthor',
            field=models.BooleanField(default=False, verbose_name='HYMENOPTHOR GR'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_kothreni',
            field=models.BooleanField(default=False, verbose_name='K OTHRENI'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_permothor',
            field=models.BooleanField(default=False, verbose_name='PERMOTHOR DUST'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_petrol',
            field=models.BooleanField(default=False, verbose_name='PETROL'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_rapetr_gel',
            field=models.BooleanField(default=False, verbose_name='RAPETR GEL'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_rat_glue',
            field=models.BooleanField(default=False, verbose_name='RAT GLUE'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_rat_poison',
            field=models.BooleanField(default=False, verbose_name='RAT POISON'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='used_snake_deter',
            field=models.BooleanField(default=False, verbose_name='SNAKE DETER'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='worker_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='العامل'),
        ),
        migrations.AlterField(
            model_name='fieldworkorder',
            name='status',
            field=models.CharField(choices=[('pending', 'لم يتم تحديد موعد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة / مغلقة'), ('incomplete', 'غير مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='fieldworkorder',
            name='work_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع العمل'),
        ),
    ]
