# Generated by Django 6.0 on 2026-04-22 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0073_field_work_order_excel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containertransferinspection',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='containertransferinspection',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_inspections_rejected', to=settings.AUTH_USER_MODEL, verbose_name='رُفض بواسطة'),
        ),
        migrations.AddField(
            model_name='containertransferinspection',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='containertransferrequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('assigned', 'بانتظار المفتش'), ('location_saved', 'تم حفظ الموقع'), ('biaa_contacted', 'تم التواصل مع بيئة'), ('biaa_transferred', 'تم نقل الحاوية'), ('report_submitted', 'تم تقديم التقرير'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='new', max_length=30, verbose_name='الحالة'),
        ),
    ]
