# Generated by Django 6.0 on 2026-04-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0074_container_transfer_rejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeedRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=100, verbose_name='رقم الشكوى')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='weed_removal/pdfs/', verbose_name='ملف PDF')),
                ('complainant_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتعامل')),
                ('complainant_mobile', models.CharField(blank=True, max_length=30, verbose_name='رقم الموبايل')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='المنطقة')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المنزل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('inspector_assigned', 'بانتظار المفتش'), ('inspection_done', 'اكتمل التفتيش'), ('supervisor_assigned', 'بانتظار المراقب'), ('work_in_progress', 'العمل جارٍ'), ('work_done', 'تم إنهاء العمل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='new', max_length=30, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
            ],
            options={
                'verbose_name': 'طلب إزالة حشائش',
                'verbose_name_plural': 'طلبات إزالة الحشائش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeedRemovalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('before', 'صور قبل العمل'), ('during', 'صور أثناء العمل'), ('after', 'صور بعد العمل')], max_length=10, verbose_name='المرحلة')),
                ('file', models.ImageField(upload_to='weed_removal/photos/', verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_photos_uploaded', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hcsd.weedremovalrequest')),
            ],
            options={
                'verbose_name': 'صورة إزالة حشائش',
                'verbose_name_plural': 'صور إزالة الحشائش',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeedRemovalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_notes', models.TextField(blank=True, verbose_name='ملاحظات التفتيش')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإتمام')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرفض')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_inspections_assigned', to=settings.AUTH_USER_MODEL, verbose_name='عُيِّن بواسطة')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_inspections_rejected', to=settings.AUTH_USER_MODEL, verbose_name='رُفض بواسطة')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='hcsd.weedremovalrequest')),
            ],
            options={
                'verbose_name': 'تفتيش إزالة حشائش',
                'verbose_name_plural': 'تفتيش طلبات إزالة الحشائش',
            },
        ),
        migrations.CreateModel(
            name='WeedRemovalSupervisorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('workers_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد العمال')),
                ('report_notes', models.TextField(blank=True, verbose_name='ملاحظات التقرير')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإتمام')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_supervisor_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='عُيِّن بواسطة')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_task', to='hcsd.weedremovalrequest')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weed_supervisor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المراقب')),
            ],
            options={
                'verbose_name': 'مهمة مراقب إزالة حشائش',
                'verbose_name_plural': 'مهام مراقبي إزالة الحشائش',
            },
        ),
        migrations.CreateModel(
            name='WeedRemovalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('pickup', 'بيك آب'), ('tractor', 'تراكتور'), ('truck', 'شاحنة'), ('loader', 'لودر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المركبة')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='العدد')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='hcsd.weedremovalsupervisortask')),
            ],
            options={
                'verbose_name': 'مركبة إزالة حشائش',
                'verbose_name_plural': 'مركبات إزالة الحشائش',
            },
        ),
    ]
