# Generated by Django 6.0 on 2026-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0076_complaint_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkorder',
            name='status',
            field=models.CharField(choices=[('pending', 'لم يتم تحديد موعد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم إنجاز الخدمة'), ('incomplete', 'غير مكتملة'), ('cancelled', 'ملغية'), ('private_company', 'شركة خاصة'), ('cust_declined', 'العميل رفض الخدمة'), ('wrong_phone', 'رقم الهاتف خاطئ'), ('phone_off', 'الهاتف مغلق'), ('no_answer', 'لا يوجد رد'), ('postponed_client', 'تأجيل من العميل'), ('gov_dept', 'جهة حكومية — يلزم إرسال موافقة'), ('other_municipal', 'تابعة لبلدية أخرى')], default='pending', max_length=30, verbose_name='الحالة'),
        ),
    ]
