# Generated by Django 6.0 on 2026-04-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0077_field_work_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='pesticides_used',
            field=models.TextField(blank=True, verbose_name='المبيدات المستخدمة'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقرير'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='report_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_reports', to=settings.AUTH_USER_MODEL, verbose_name='أدخل التقرير'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='supervisor_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراقب'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='vehicles_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد السيارات'),
        ),
        migrations.AlterField(
            model_name='fieldworkorder',
            name='status',
            field=models.CharField(choices=[('private_company', 'شركة خاصة'), ('cust_declined', 'العميل رفض الخدمة'), ('wrong_phone', 'رقم الهاتف خاطئ'), ('phone_off', 'الهاتف مغلق'), ('no_answer', 'لا يوجد رد'), ('completed', 'تم إنجاز الخدمة'), ('postponed_client', 'تأجيل من العميل'), ('gov_dept', 'جهة حكومية — يلزم إرسال موافقة'), ('other_municipal', 'تابعة لبلدية أخرى')], default='private_company', max_length=30, verbose_name='الحالة'),
        ),
    ]
