# Generated by Django 6.0 on 2026-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0078_field_work_supervisor_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedremovalinspection',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='weedremovalinspection',
            name='location_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الموقع'),
        ),
        migrations.AddField(
            model_name='weedremovalinspection',
            name='location_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت حفظ الموقع'),
        ),
        migrations.AddField(
            model_name='weedremovalinspection',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
