# Generated by Django 6.0 on 2026-04-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0079_weed_inspection_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDisposalInspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pirmet_documents/waste_disposal_inspection_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disposal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='hcsd.wastedisposalrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_inspection_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
