# Generated by Django 6.0 on 2026-04-28 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0080_waste_disposal_inspection_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='location_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت حفظ الموقع'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='location_saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_locations_saved', to=settings.AUTH_USER_MODEL, verbose_name='حفظ الموقع'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='no_answer_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='field_work/no_answer/', verbose_name='صورة عدم الرد'),
        ),
    ]
