# Generated by Django 6.0 on 2026-04-29 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0081_field_work_location_and_no_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المراقب المعيّن'),
        ),
    ]
