# Generated by Django 6.0 on 2026-04-29 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0083_create_fw_supervisor_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_received', to=settings.AUTH_USER_MODEL, verbose_name='المراقب المستلِم'),
        ),
    ]
