# Generated by Django 6.0 on 2026-04-29 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0084_field_work_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorkSupervisorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200, verbose_name='المنطقة')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fw_area_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='عُيِّن بواسطة')),
                ('supervisor', models.ForeignKey(limit_choices_to={'groups__name__in': ['fw_supervisor', 'Field Work Supervisor']}, on_delete=django.db.models.deletion.CASCADE, related_name='fw_supervisor_areas', to=settings.AUTH_USER_MODEL, verbose_name='المراقب')),
            ],
            options={
                'verbose_name': 'منطقة مراقب عمل ميداني',
                'verbose_name_plural': 'مناطق مراقبي العمل الميداني',
                'ordering': ['supervisor__first_name', 'area'],
                'unique_together': {('supervisor', 'area')},
            },
        ),
    ]
