# Generated by Django 6.0 on 2026-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0086_fix_new_company_violation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='spray_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='مكان الرش'),
        ),
        migrations.AlterField(
            model_name='fieldworkorder',
            name='status',
            field=models.CharField(choices=[('private_company', 'شركة خاصة'), ('cust_declined', 'العميل رفض الخدمة'), ('wrong_phone', 'رقم الهاتف خاطئ'), ('phone_off', 'الهاتف مغلق'), ('no_answer', 'لا يوجد رد'), ('completed', 'تم إنجاز الخدمة'), ('postponed_client', 'تأجيل من العميل'), ('gov_dept', 'جهة حكومية — يلزم إرسال موافقة'), ('other_municipal', 'تابعة لبلدية أخرى'), ('closed_private_building', 'مغلق — شركة نظافة خاصة (داخل بناية)'), ('closed_no_answer', 'مغلق — لم يرد العميل على الهاتف'), ('closed_other_municipal', 'مغلق — تابع لبلدية أخرى')], default='private_company', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='wastedisposalrequest',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Waiting for Disposal Payment'), ('inspection_pending', 'Inspection Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled_admin', 'Cancelled Administratively')], default='payment_pending', max_length=30),
        ),
    ]
