# Generated by Django 6.0 on 2026-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0087_field_work_spray_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='client_signature',
            field=models.TextField(blank=True, verbose_name='توقيع العميل'),
        ),
        migrations.AddField(
            model_name='fieldworkorder',
            name='supervisor_signature',
            field=models.TextField(blank=True, verbose_name='توقيع المراقب'),
        ),
    ]
