# Generated by Django 6.0 on 2026-05-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0088_field_work_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='spray_entries',
            field=models.JSONField(blank=True, default=list, verbose_name='سجلات الرش'),
        ),
    ]
