# Generated by Django 6.0 on 2026-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0089_field_work_spray_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='building_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع المبنى'),
        ),
    ]
