# Generated by Django 6.0 on 2026-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0090_field_work_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='postponed_until',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التأجيل'),
        ),
    ]
