# Generated by Django 6.0 on 2026-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0091_field_work_postponed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الوصول'),
        ),
    ]
