# Generated by Django 6.0 on 2026-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0094_companychangelog_location_saved_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginerstatuslog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('public_health_cert_uploaded', 'Public Health Certificate Uploaded'), ('termite_cert_uploaded', 'Termite Certificate Uploaded'), ('leave_recorded', 'Leave Recorded'), ('leave_closed', 'Leave Closed')], max_length=40),
        ),
    ]
