# Generated by Django 6.0 on 2026-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0096_pests_found_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkorder',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('private_company', 'شركة خاصة'), ('cust_declined', 'العميل رفض الخدمة'), ('wrong_phone', 'رقم الهاتف خاطئ'), ('phone_off', 'الهاتف مغلق'), ('no_answer', 'لا يوجد رد'), ('completed', 'تم إنجاز الخدمة'), ('postponed_client', 'تأجيل من العميل'), ('gov_dept', 'جهة حكومية — يلزم إرسال موافقة'), ('other_municipal', 'تابعة لبلدية أخرى'), ('closed_private_building', 'مغلق — شركة نظافة خاصة (داخل بناية)'), ('closed_no_answer', 'مغلق — لم يرد العميل على الهاتف'), ('closed_other_municipal', 'مغلق — تابع لبلدية أخرى'), ('closed_observation', 'مغلق — ملاحظة'), ('closed_low_infestation', 'مغلق — تفشٍ خفيف'), ('closed_moderate_infestation', 'مغلق — تفشٍ متوسط'), ('closed_high_infestation', 'مغلق — تفشٍ شديد'), ('closed_out_of_service', 'مغلق — خارج نطاق الخدمة'), ('closed_customer_refused', 'مغلق — العميل رفض الخدمة'), ('closed_mobile_off', 'مغلق — هاتف العميل مغلق'), ('closed_not_attending', 'مغلق — العميل لا يرد على المكالمات'), ('closed_not_available', 'مغلق — العميل غير متاح'), ('closed_scheduled_client', 'مغلق — تم الجدولة من قِبل العميل')], default='new', max_length=30, verbose_name='الحالة'),
        ),
    ]
