# Generated by Django 6.0 on 2026-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0097_fieldworkorder_status_default_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkphoto',
            name='phase',
            field=models.CharField(choices=[('work', 'صور العمل'), ('before', 'قبل العمل'), ('during', 'أثناء العمل'), ('after', 'بعد العمل')], max_length=10, verbose_name='المرحلة'),
        ),
    ]
