# Generated by Django 6.0 on 2026-05-07 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0098_fieldworkphoto_add_work_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorkSupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('admin_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الإداري')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fw_supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مراقب عمل ميداني',
                'verbose_name_plural': 'ملفات مراقبي العمل الميداني',
            },
        ),
    ]
