# Generated by Django 6.0 on 2026-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0099_fieldwork_supervisor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='report_findings',
            field=models.JSONField(blank=True, default=list, verbose_name='الملاحظات الميدانية'),
        ),
        migrations.AlterField(
            model_name='weedremovalvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('pickup', 'بيك آب'), ('bobcat', 'بوبكات'), ('tractor', 'تراكتور'), ('truck', 'شاحنة'), ('loader', 'لودر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المركبة'),
        ),
    ]
