# Generated by Django 6.0 on 2026-05-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0101_fieldwork_list_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirmetclearance',
            name='status',
            field=models.CharField(choices=[('order_received', 'تم استلام الطلب'), ('inspection_payment_pending', 'بانتظار دفع التفتيش'), ('review_pending', 'بانتظار مراجعة المفتش'), ('needs_completion', 'يحتاج استكمال'), ('approved', 'معتمد من المفتش'), ('payment_pending', 'بانتظار الدفع'), ('issued', 'صادر'), ('inspection_pending', 'بانتظار التفتيش'), ('inspection_completed', 'اكتمل التفتيش'), ('violation_payment_link_pending', 'بانتظار رابط دفع المخالفة'), ('violation_payment_pending', 'بانتظار دفع المخالفة'), ('head_approved', 'الاعتماد النهائي'), ('closed_requirements_pending', 'مغلق - متطلبات معلقة'), ('cancelled_admin', 'ملغى إدارياً'), ('disposal_approved', 'موافقة على التخلص'), ('disposal_rejected', 'رفض التخلص')], default='order_received', max_length=30),
        ),
        migrations.AlterField(
            model_name='wastedisposalrequest',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'بانتظار الدفع'), ('inspection_pending', 'بانتظار التفتيش'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('cancelled_admin', 'ملغى إدارياً')], default='payment_pending', max_length=30),
        ),
        migrations.CreateModel(
            name='EngineerCompanyRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_removals', to='hcsd.company')),
                ('enginer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_removals', to='hcsd.enginer')),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_removals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل إزالة مهندس',
                'verbose_name_plural': 'سجلات إزالة المهندسين',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineerRemovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='engineer_removals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('removal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hcsd.engineercompanyremoval')),
            ],
            options={
                'verbose_name': 'مستند إزالة مهندس',
                'verbose_name_plural': 'مستندات إزالة المهندسين',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
