# Generated by Django 6.0 on 2026-05-21 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0102_engineer_company_removal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginerstatuslog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('public_health_cert_uploaded', 'Public Health Certificate Uploaded'), ('termite_cert_uploaded', 'Termite Certificate Uploaded'), ('leave_recorded', 'Leave Recorded'), ('leave_closed', 'Leave Closed'), ('removed_from_company', 'Removed From Company')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_number', models.CharField(blank=True, max_length=150, verbose_name='الرقم الإداري')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
