# Generated by Django 6.0 on 2026-05-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0104_backfill_user_profile_admin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weedremovalrequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('inspector_assigned', 'بانتظار المفتش'), ('inspection_done', 'اكتمل التفتيش'), ('supervisor_assigned', 'بانتظار المراقب'), ('work_in_progress', 'العمل جارٍ'), ('work_paused', 'العمل متوقف مؤقتاً'), ('work_done', 'تم إنهاء العمل'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='new', max_length=30, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='WeedRemovalWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='وقت البدء')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('end_type', models.CharField(blank=True, choices=[('postponed', 'مؤجل'), ('completed', 'مكتمل')], max_length=10, null=True, verbose_name='نوع الإنهاء')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='hcsd.weedremovalsupervisortask', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'جلسة عمل إزالة حشائش',
                'verbose_name_plural': 'جلسات عمل إزالة الحشائش',
                'ordering': ['started_at'],
            },
        ),
    ]
