# Generated by Django 6.0 on 2026-05-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0105_weed_work_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedremovalworksession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات التقرير'),
        ),
        migrations.AddField(
            model_name='weedremovalworksession',
            name='workers_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد العمال'),
        ),
        migrations.CreateModel(
            name='WeedRemovalSessionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('pickup', 'بيك آب'), ('bobcat', 'بوبكات'), ('tractor', 'تراكتور'), ('truck', 'شاحنة'), ('loader', 'لودر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المركبة')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='العدد')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='hcsd.weedremovalworksession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'مركبة جلسة إزالة حشائش',
                'verbose_name_plural': 'مركبات جلسات إزالة الحشائش',
            },
        ),
    ]
