# Generated by Django 6.0 on 2026-05-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0106_weed_session_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedremovalphoto',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='hcsd.weedremovalworksession', verbose_name='الجلسة'),
        ),
    ]
