# Generated by Django 6.0 on 2026-06-05 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0107_weed_photo_session_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorkOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء الأمر'), ('assigned', 'تعيين مراقب'), ('reassigned', 'إعادة تعيين مراقب'), ('unassigned', 'إلغاء تعيين مراقب'), ('received', 'استلام الأمر'), ('status_changed', 'تغيير الحالة'), ('postponed', 'تأجيل الموعد'), ('closed', 'إغلاق الأمر'), ('completed', 'إتمام الخدمة')], max_length=20, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت')),
                ('from_value', models.CharField(blank=True, max_length=200, verbose_name='من')),
                ('to_value', models.CharField(blank=True, max_length=200, verbose_name='إلى')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fw_logs', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hcsd.fieldworkorder', verbose_name='الأمر')),
            ],
            options={
                'verbose_name': 'سجل تغيير',
                'verbose_name_plural': 'سجل تغييرات الأوامر',
                'ordering': ['-timestamp'],
            },
        ),
    ]
