# Generated by Django 6.0 on 2026-06-10 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0110_add_order_received_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldworkorder',
            options={},
        ),
        migrations.AddIndex(
            model_name='fieldworkorder',
            index=models.Index(fields=['status', 'created_at'], name='fw_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldworkorder',
            index=models.Index(fields=['request_date'], name='fw_request_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldworkorder',
            index=models.Index(fields=['assigned_supervisor', 'status'], name='fw_sup_status_idx'),
        ),
    ]
