# Generated by Django 6.0 on 2026-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0111_fw_order_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='complaint_source',
            field=models.CharField(blank=True, choices=[('electronic', 'طلبات إلكترونية'), ('correspondence', 'تراسل'), ('office', 'طلبات مكتب')], default='', max_length=20, verbose_name='مصدر الشكوى'),
        ),
    ]
