# Generated by Django 6.0 on 2026-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0112_add_complaint_source_to_fieldworkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkorder',
            name='complaint_source',
            field=models.CharField(blank=True, choices=[('electronic', 'طلبات إلكترونية'), ('correspondence', 'تراسل'), ('office', 'طلبات مكتب'), ('hotline', 'خط ساخن')], default='', max_length=20, verbose_name='مصدر الشكوى'),
        ),
    ]
