# Generated by Django 6.0 on 2026-07-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0113_add_hotline_complaint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('assigned_inspector', 'تم تعيين مفتش'), ('inspection_done', 'اكتمل التفتيش'), ('assigned_supervisor', 'تم تعيين مراقب'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الإنجاز'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
