# Generated by Django 6.0 on 2026-07-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0114_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintresolution',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintphoto',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintinspection',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintinspection',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='complaintinspection',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='complaintmaterial',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='complaintphoto',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='complaintresolution',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='complaintresolution',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='complaintvehicle',
            name='resolution',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintInspection',
        ),
        migrations.DeleteModel(
            name='ComplaintMaterial',
        ),
        migrations.DeleteModel(
            name='ComplaintPhoto',
        ),
        migrations.DeleteModel(
            name='ComplaintResolution',
        ),
        migrations.DeleteModel(
            name='ComplaintVehicle',
        ),
    ]
