# Generated by Django 6.0 on 2026-07-23 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0115_remove_complaintresolution_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_requests_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_payments_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='reference_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrequest',
            name='reference_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_disposal_references_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
