# Generated by Django 6.0 on 2026-07-24 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0116_wastedisposalrequest_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkorder',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('excel', 'مستورد من Excel'), ('recurring', 'طلب دوري متكرر')], db_index=True, default='manual', max_length=10, verbose_name='المصدر'),
        ),
        migrations.CreateModel(
            name='FieldWorkRecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الموقع')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتعامل')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='الموبايل')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='المنطقة')),
                ('street_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الشارع')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المنزل')),
                ('pest_types', models.CharField(blank=True, max_length=300, verbose_name='نوع الحشرات')),
                ('complaint_source', models.CharField(blank=True, choices=[('electronic', 'طلبات إلكترونية'), ('correspondence', 'تراسل'), ('office', 'طلبات مكتب'), ('hotline', 'خط ساخن')], default='', max_length=20, verbose_name='مصدر الشكوى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='يوم التكرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('last_generated_on', models.DateField(blank=True, null=True, verbose_name='آخر إنشاء تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_recurring_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'طلب دوري متكرر',
                'verbose_name_plural': 'الطلبات الدورية المتكررة',
                'ordering': ['weekday', '-created_at'],
            },
        ),
    ]
