# Generated by Django 6.0 on 2026-07-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0117_alter_fieldworkorder_source_fieldworkrecurringorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkorder',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='hcsd.fieldworkrecurringorder', verbose_name='الطلب الدوري المصدر'),
        ),
    ]
