# Generated by Django 6.0 on 2026-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0118_fieldworkorder_recurring_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworkrecurringorder',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'يوم اثنين'), (1, 'يوم ثلاثاء'), (2, 'يوم أربعاء'), (3, ' يوم خميس'), (4, ' يوم جمعة'), (5, ' يوم سبت '), (6, 'يوم أحد')], verbose_name='يوم التكرار'),
        ),
    ]
