# Generated by Django 6.0 on 2026-09-02 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0119_alter_fieldworkrecurringorder_weekday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RodentControlBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البناية')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='رقم البناية')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='المنطقة')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='قيد المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodent_buildings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بناية متابعة مصايد',
                'verbose_name_plural': 'بنايات متابعة المصايد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RodentControlVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='شهر المتابعة')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة')),
                ('inspected', models.BooleanField(default=False, verbose_name='تم التفتيش')),
                ('infested', models.BooleanField(default=False, verbose_name='بها إصابة')),
                ('damaged', models.BooleanField(default=False, verbose_name='تالفة')),
                ('newly_installed', models.BooleanField(default=False, verbose_name='تم تركيب مصيدة جديدة')),
                ('replenished', models.BooleanField(default=False, verbose_name='تم تعبئتها')),
                ('rodenticide_type', models.CharField(blank=True, max_length=150, verbose_name='نوع المادة')),
                ('rodenticide_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الزيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hcsd.rodentcontrolbuilding')),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodent_visits_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'زيارة متابعة مصيدة',
                'verbose_name_plural': 'زيارات متابعة المصايد',
                'ordering': ['-period_start'],
                'unique_together': {('building', 'period_start')},
            },
        ),
    ]
