# Generated by Django 6.0 on 2026-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0120_rodentcontrolbuilding_rodentcontrolvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='burrows_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الجحور المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='burrows_outside_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الجحور الخارجية'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='manholes_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المناهيل المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='manholes_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المناهيل المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='manholes_treated_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المناهيل المعالجة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='manholes_treated_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='كمية معالجة المناهيل'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_damaged_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المصايد التالفة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المصايد المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المصايد المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_lock_ok',
            field=models.BooleanField(default=True, verbose_name='قفل المصيدة سليم'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_new_installed_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المصايد المركبة حديثاً'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rbs_replenished_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المصايد المعاد تعبئتها'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='stick_change_ok',
            field=models.BooleanField(default=True, verbose_name='تم تغيير اللاصقة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='team_leader_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='team_leader_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم قائد الفريق'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الخروج'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='trees_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='النخيل المصاب'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='trees_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي النخيل المفتش'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='trees_treated_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='النخيل المعالج'),
        ),
    ]
