# Generated by Django 6.0 on 2026-09-03 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0121_rodentcontrolvisit_burrows_infested_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='campaign/photos/', verbose_name='صورة')),
                ('building_number', models.CharField(blank=True, max_length=50, verbose_name='رقم البناية')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='المنطقة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة المفتش')),
                ('noted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_requests_created', to=settings.AUTH_USER_MODEL)),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب متابعة حملة',
                'verbose_name_plural': 'طلبات متابعة الحملة',
                'ordering': ['-created_at'],
            },
        ),
    ]
