# Generated by Django 6.0 on 2026-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0122_campaignrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط الموقع على خرائط قوقل'),
        ),
    ]
