# Generated by Django 6.0 on 2026-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0123_campaignrequest_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='infestation_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='مكان الإصابة'),
        ),
    ]
