# Generated by Django 6.0 on 2026-09-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0124_campaignrequest_infestation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignrequest',
            name='location',
        ),
    ]
