# Generated by Django 6.0 on 2026-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0126_auto_close_weed_removal_work_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='bldg_villa_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المباني/الفلل المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='bldg_villa_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المباني/الفلل المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='construction_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الإنشاءات المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='construction_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي الإنشاءات المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='electrical_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الغرف الكهربائية المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='electrical_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي الغرف الكهربائية المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='gov_offices_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المكاتب الحكومية'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='masjed_infested_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المساجد المصابة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='masjed_inspected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المساجد المفتشة'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_facorat_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='FACORAT PELLETS'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_nocurat_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='NOCURAT PARAFFINATO'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_protect_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Protect Sensation 2in1'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_sellioxid_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='SELLIOX D'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_surefire_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='SUREFIRE ALL WEATHER'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_vertox_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VERTOX Okta Blocks'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='rodenticide_victor_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VICTOR V FAST KILL'),
        ),
        migrations.AddField(
            model_name='rodentcontrolvisit',
            name='technicians_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الفنيين'),
        ),
    ]
