# Generated by Django 6.0 on 2026-09-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0129_remove_bogus_total_building'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rodentcontrolvisit',
            unique_together=set(),
        ),
    ]
