# Generated by Django 6.0 on 2026-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0130_alter_rodentcontrolvisit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='action_type',
            field=models.CharField(blank=True, choices=[('violation', 'مخالفة'), ('warning', 'إنذار'), ('followup', 'متابعة')], max_length=20, verbose_name='نوع الإجراء'),
        ),
    ]
