# Generated by Django 6.0 on 2026-09-08 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0131_campaignrequest_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('violation', 'مخالفة'), ('warning', 'إنذار'), ('followup', 'متابعة')], max_length=20, verbose_name='نوع الإجراء')),
                ('note', models.TextField(blank=True, verbose_name='الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_action_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='hcsd.campaignrequest')),
            ],
            options={
                'verbose_name': 'سجل إجراء حملة',
                'verbose_name_plural': 'سجل إجراءات الحملة',
                'ordering': ['-created_at'],
            },
        ),
    ]
