# Generated by Django 6.0 on 2026-09-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0132_campaignactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='التاريخ')),
                ('area_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المنطقة')),
                ('google_maps_url', models.URLField(blank=True, max_length=500, verbose_name='رابط خرائط قوقل')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('infested_manholes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مناهيل مصابة')),
                ('infested_outside', models.PositiveIntegerField(blank=True, null=True, verbose_name='إصابة خارجية')),
                ('total_infested_bldg', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المباني المصابة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_visits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'زيارة متابعة الحدائق',
                'verbose_name_plural': 'زيارات متابعة الحدائق',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
