# Generated by Django 6.0 on 2026-09-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0133_gardenvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardenvisit',
            options={'ordering': ['-visit_date', '-created_at'], 'verbose_name': 'زيارة متابعة المناطق', 'verbose_name_plural': 'زيارات متابعة المناطق'},
        ),
    ]
