# Generated by Django 6.0 on 2026-09-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0134_alter_gardenvisit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignactionlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('violation', 'مخالفة'), ('followup', 'متابعة')], max_length=20, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='action_type',
            field=models.CharField(blank=True, choices=[('violation', 'مخالفة'), ('followup', 'متابعة')], max_length=20, verbose_name='نوع الإجراء'),
        ),
    ]
