# Generated by Django 6.0 on 2026-09-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0135_alter_campaignactionlog_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المفتش المستلم'),
        ),
    ]
