# Generated by Django 6.0 on 2026-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0136_campaignrequest_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenvisit',
            name='location_details',
            field=models.CharField(blank=True, help_text='لتمييز المواقع التي تشترك في نفس اسم المنطقة، مثال: بجانب مسجد كذا، رقم المبنى 12', max_length=200, verbose_name='تفاصيل الموقع'),
        ),
    ]
