# Generated by Django 6.0 on 2026-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0137_gardenvisit_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenvisit',
            name='infestation_type',
            field=models.CharField(blank=True, help_text='قيم مفصولة بفاصلة من: norway_rat, roof_rat, house_mouse', max_length=100, verbose_name='نوع الإصابة'),
        ),
    ]
