# Generated by Django 6.0 on 2026-09-11 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0138_gardenvisit_infestation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenAreaReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=150)),
                ('period_start', models.DateField()),
                ('action', models.CharField(choices=[('reviewed', 'تمت المراجعة'), ('unreviewed', 'إلغاء المراجعة')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_area_review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل مراجعة منطقة',
                'verbose_name_plural': 'سجلات مراجعة المناطق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenAreaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=150)),
                ('period_start', models.DateField(verbose_name='الشهر')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_area_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مراجعة منطقة',
                'verbose_name_plural': 'مراجعات المناطق',
                'ordering': ['area_name'],
                'unique_together': {('area_name', 'period_start')},
            },
        ),
    ]
