# Generated by Django 6.0 on 2026-09-14 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0139_gardenareareview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenVisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.PositiveIntegerField(verbose_name='رقم مكان الإصابة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف مكان الإصابة')),
                ('file', models.ImageField(upload_to='garden_visits/photos/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garden_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hcsd.gardenvisit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_visit_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صورة مكان إصابة',
                'verbose_name_plural': 'صور أماكن الإصابة',
                'ordering': ['spot_number', 'id'],
            },
        ),
    ]
