# Generated by Django 6.0 on 2026-09-17 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0140_gardenvisitphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenVisitChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المنطقة')),
                ('action', models.CharField(choices=[('created', 'تمت الإضافة'), ('updated', 'تحديث بيانات الإصابة'), ('location_updated', 'تحديث الموقع'), ('review_toggled', 'تغيير حالة المراجعة'), ('deleted', 'تم الحذف')], max_length=30, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_change_logs', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='hcsd.gardenvisit')),
            ],
            options={
                'verbose_name': 'سجل تغييرات المنطقة',
                'verbose_name_plural': 'سجل تغييرات المناطق',
                'ordering': ['-created_at'],
            },
        ),
    ]
