# Generated by Django 6.0 on 2026-09-22 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0141_gardenvisitchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('area_name', models.CharField(max_length=150, verbose_name='المنطقة')),
                ('team_leader_name', models.CharField(blank=True, max_length=150, verbose_name='قائد الفريق')),
                ('team_leader_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي')),
                ('start_from', models.CharField(blank=True, max_length=200, verbose_name='بدأ من')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('total_bldg_villa', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المباني/الفلل')),
                ('infested_bldg_villa', models.PositiveIntegerField(blank=True, null=True, verbose_name='مباني/فلل مصابة')),
                ('total_manholes', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المناهيل')),
                ('treated_manholes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مناهيل معالجة')),
                ('infested_manholes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مناهيل مصابة')),
                ('total_outside', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي الإصابة الخارجية')),
                ('infested_outside', models.PositiveIntegerField(blank=True, null=True, verbose_name='إصابة خارجية مصابة')),
                ('total_construction', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي الإنشاءات')),
                ('infested_construction', models.PositiveIntegerField(blank=True, null=True, verbose_name='إنشاءات مصابة')),
                ('total_masjid', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي المساجد')),
                ('infested_masjid', models.PositiveIntegerField(blank=True, null=True, verbose_name='مساجد مصابة')),
                ('total_tree', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي النخيل/الأشجار')),
                ('treated_tree', models.PositiveIntegerField(blank=True, null=True, verbose_name='أشجار معالجة')),
                ('infested_tree', models.PositiveIntegerField(blank=True, null=True, verbose_name='أشجار مصابة')),
                ('electrical_rooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='غرف كهربائية')),
                ('infested_ers', models.PositiveIntegerField(blank=True, null=True, verbose_name='غرف كهربائية مصابة')),
                ('gov_office', models.PositiveIntegerField(blank=True, null=True, verbose_name='مكاتب حكومية')),
                ('rodenticide_1_name', models.CharField(blank=True, max_length=150, verbose_name='المبيد 1')),
                ('rodenticide_1_qty', models.CharField(blank=True, max_length=50, verbose_name='كمية المبيد 1')),
                ('rodenticide_2_name', models.CharField(blank=True, max_length=150, verbose_name='المبيد 2')),
                ('rodenticide_2_qty', models.CharField(blank=True, max_length=50, verbose_name='كمية المبيد 2')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير يومي - متابعة المناطق',
                'verbose_name_plural': 'تقارير يومية - متابعة المناطق',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
