# Generated by Django 6.0 on 2026-10-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcsd', '0142_gardendailyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldworkorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'أمر عمل ميداني', 'verbose_name_plural': 'أوامر العمل الميداني'},
        ),
    ]
